all:
	make exo1
	make exo2
	make exo3
	make exo4
	make exo5

exo1: exo1.c
	gcc exo1.c -o exo1_exe -Wall -ansi

exo2: exo2.c
	gcc exo2.c -o exo2_exe -Wall -ansi

exo3: exo3.c
	gcc exo3.c -o exo3_exe -Wall -ansi

exo4: exo4.c
	gcc exo4.c -o exo4_exe -Wall -ansi

exo5: exo5.c
	gcc exo5.c -o exo5_exe -Wall -ansi

clean:
	rm *_exe